### Importación de Bibliotecas

In [2]:
import numpy as np
import matplotlib.pyplot as plt

### Datos de Entrada y Preparación de Matrices

In [ ]:
X = np.array([
    [80, 3], 
    [120, 3],
    [100, 2],
    [150, 4]])

y = np.array([310, 390, 325,530])

X_bias = np.c_[np.ones((X.shape[0], 1)), X]

A_original = X_bias.T @ X_bias
b = X_bias.T @ y

### Determiante y Rango de la Matriz A Original

In [10]:
det_orig = np.linalg.det(A_original)
rank_orig = np.linalg.matrix_rank(A_original)
print(f'Determinante de A: {det_orig:.3f}')
print(f'Rango de A: {rank_orig} (Matriz de tamaño {A_original.shape[0]}x{A_original.shape[1]})')

Determinante de A: 11400.000
Rango de A: 3 (Matriz de tamaño 3x3)


### Determinante y Rango de la Matrices Adulteradas

In [18]:
habitación_doble = X[:, 1] * 2
X_adulterada = np.c_[X, habitación_doble]
X_adulterada_bias = np.c_[np.ones((X_adulterada.shape[0], 1)), X_adulterada]
print(f'Matriz X_adulterada_bias:\n{X_adulterada_bias}')

Matriz X_adulterada_bias:
[[  1.  80.   3.   6.]
 [  1. 120.   3.   6.]
 [  1. 100.   2.   4.]
 [  1. 150.   4.   8.]]


In [17]:
det_X_adulterada = np.linalg.det(X_adulterada_bias)
print(f'Determinante de X adulterada: {det_X_adulterada:.3f}')
rank_X_adulterada = np.linalg.matrix_rank(X_adulterada_bias)
print(f'Rango de X adulterada: {rank_X_adulterada} (Matriz de tamaño {X_adulterada_bias.shape[0]}x{X_adulterada_bias.shape[1]})')

Determinante de X adulterada: 0.000
Rango de X adulterada: 3 (Matriz de tamaño 4x4)


In [19]:
A_adulterada = X_adulterada_bias.T @ X_adulterada_bias
det_adul = np.linalg.det(A_adulterada)
rank_adul = np.linalg.matrix_rank(A_adulterada)
print(f'Matriz A adulterada:\n{A_adulterada}')
print(f'Determinante de A adulterada: {det_adul:.3f}')
print(f'Rango de A adulterada: {rank_adul} (Matriz de tamaño {A_adulterada.shape[0]}x{A_adulterada.shape[1]})')

Matriz A adulterada:
[[4.00e+00 4.50e+02 1.20e+01 2.40e+01]
 [4.50e+02 5.33e+04 1.40e+03 2.80e+03]
 [1.20e+01 1.40e+03 3.80e+01 7.60e+01]
 [2.40e+01 2.80e+03 7.60e+01 1.52e+02]]
Determinante de A adulterada: 0.000
Rango de A adulterada: 3 (Matriz de tamaño 4x4)
