## Importación de Bibliotecas

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:

calificaciones_reales=np.array([5,1])
calificaciones_predichas=np.array([4.5,2.5])
print(f'Calificaciones Reales: {calificaciones_reales}')
print(f'Calificaciones Predichas: {calificaciones_predichas}')

error_calculado=calificaciones_reales - calificaciones_predichas
print(f'Error Calculado: {error_calculado}')

Calificaciones Reales: [5 1]
Calificaciones Predichas: [4.5 2.5]
Error Calculado: [ 0.5 -1.5]


In [5]:
porcentaje_error=(error_calculado / calificaciones_reales) * 100
print(f'Porcentaje de Error: {porcentaje_error}')

Porcentaje de Error: [  10. -150.]


In [6]:
ventas_enero=np.array([
    [200,220,250],
    [150,180,200],
    [300,320,350]
    ])

ventas_febrero=np.array([
    [210,230,260],
    [160,190,210],
    [310,330,360]
    ])

In [7]:
ventas_totales=ventas_enero + ventas_febrero
print(f'Ventas Totales:\n{ventas_totales}')

Ventas Totales:
[[410 450 510]
 [310 370 410]
 [610 650 710]]
