### Importación de Bibliotecas

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Normas de Vectores

In [ ]:
vector1=np.array([3,4,-5])  
vector2=np.array([1,0,2])

norma_vector1=np.linalg.norm(vector1)
print(f'Norma del Vector 1: {norma_vector1:.3f}')
norma_vector2=np.linalg.norm(vector2)
print(f'Norma del Vector 2: {norma_vector2:.3f}')

normaL1_vector1=np.linalg.norm(vector1,1)
print(f'Norma L1 del Vector 1: {normaL1_vector1:.3f}')
normaL1_vector2=np.linalg.norm(vector2,1)
print(f'Norma L1 del Vector 2: {normaL1_vector2:.3f}')

normaL0_vector1=np.linalg.norm(vector1,0)
print(f'Norma L0 del Vector 1: {normaL0_vector1:.3f}')
normaL0_vector2=np.linalg.norm(vector2,0)
print(f'Norma L0 del Vector 2: {normaL0_vector2:.3f}')

normainf_vector1=np.linalg.norm(vector1,np.inf)
print(f'Norma Inf del Vector 1: {normainf_vector1:.3f}')
normainf_vector2=np.linalg.norm(vector2,np.inf)
print(f'Norma Inf del Vector 2: {normainf_vector2:.3f}')


Norma del Vector 1: 7.071
Norma del Vector 2: 2.236
Norma L1 del Vector 1: 12.000
Norma L1 del Vector 2: 3.000
Norma L0 del Vector 1: 3.000
Norma L0 del Vector 2: 2.000
Norma Inf del Vector 1: 5.000
Norma Inf del Vector 2: 2.000
Norma del Tensor 1: 14.283
Norma del Tensor 2: 14.283
Norma de la Matriz 1: 16.882
Norma de la Matriz 2: 16.882
Producto Interno entre Vector 1 y Vector 2: -7.000
Producto Matricial entre Matriz 1 y Matriz 2:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


### Norma de Matrices

In [ ]:
Matriz1=np.array([[1,2,3],[4,5,6],[7,8,9]])
Matriz2=np.array([[9,8,7],[6,5,4],[3,2,1]])

norma_matriz1=np.linalg.norm(Matriz1)
print(f'Norma de la Matriz 1: {norma_matriz1:.3f}')
norma_matriz2=np.linalg.norm(Matriz2)
print(f'Norma de la Matriz 2: {norma_matriz2:.3f}')




### Norma de Tensores

In [3]:
Tensor1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
Tensor2=np.array([[[8,7],[6,5]],[[4,3],[2,1]]])

norma_tensor1=np.linalg.norm(Tensor1)
print(f'Norma del Tensor 1: {norma_tensor1:.3f}')
norma_tensor2=np.linalg.norm(Tensor2)
print(f'Norma del Tensor 2: {norma_tensor2:.3f}')

Norma del Tensor 1: 14.283
Norma del Tensor 2: 14.283


### Producto Interno de Vectores y Matrices

In [ ]:
producto_interno=np.dot(vector1,vector2)
print(f'Producto Interno entre Vector 1 y Vector 2: {producto_interno:.3f}')
producto_matricial=np.dot(Matriz1,Matriz2)
print(f'Producto Matricial entre Matriz 1 y Matriz 2:\n{producto_matricial}')

Producto Interno entre Vector 1 y Vector 2: -7.000
Producto Matricial entre Matriz 1 y Matriz 2:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]
